export enum GeographicLocation {
  HIMALAYAN = 'HIMALAYAN',
  FOREST = 'FOREST',
  NORTHERN_PLAINS = 'NORTHERN_PLAINS',
  RIVERINE = 'RIVERINE',
  DESERT = 'DESERT',
  PENINSULAR = 'PENINSULAR',
  COASTAL_AND_GHATS = 'COASTAL_AND_GHATS',
  ISLAND = 'ISLAND',
  OTHERS = 'OTHERS',
}
